services:
  mycalbook:
    image: git.eidenz.moe/eidenz/mycalbook:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mycalbook
    restart: unless-stopped
    ports:
      - "8080:5001"
    volumes:
      # This persists the SQLite database file outside the container
      - ./database:/app/server/database
      - ./uploads:/app/server/public/uploads
    env_file:
      # Load environment variables from this file
      - .env
    environment:
      - NODE_ENV=production